replicaCount: 3

image:
  repository: devops-hilltop
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    database: "devops_hilltop"
  primary:
    persistence:
      enabled: true
      size: 8Gi

env:
  NODE_ENV: "production"
  PORT: "5000"
  APP_NAME: "DevOps with Hilltop"

secrets:
  DATABASE_URL: "postgresql://postgres:changeme@devops-hilltop-postgresql:5432/devops_hilltop"
  PGUSER: "postgres"
  PGPASSWORD: "changeme"
  PGHOST: "devops-hilltop-postgresql"
  PGPORT: "5432"
  PGDATABASE: "devops_hilltop"