apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: devops-hilltop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-storage-class
  resources:
    requests:
      storage: 10Gi