apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops-hilltop
  labels:
    app: postgres
type: Opaque
data:
  password: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password (base64 encoded)