apiVersion: v1
kind: Secret
metadata:
  name: devops-hilltop-secret
  namespace: devops-hilltop
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzX3Bhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9kZXZvcHNfaGlsbHRvcA==
  PGUSER: cG9zdGdyZXM=
  PGPASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  PGHOST: cG9zdGdyZXMtc2VydmljZQ==
  PGPORT: NTQzMg==
  PGDATABASE: ZGV2b3BzX2hpbGx0b3A=