apiVersion: v1
kind: Service
metadata:
  name: devops-hilltop-service
  namespace: devops-hilltop
  labels:
    app: devops-platform
    component: web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "devops-hilltop-cluster-public-subnet-1,devops-hilltop-cluster-public-subnet-2,devops-hilltop-cluster-public-subnet-3"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: devops-platform
    component: web